work_dir: work_dir/MS-AimCLR/X-View/1_bone_kinectground+smplx42_fullrandom_extended

# feeder
train_feeder: feeder.ntu_feeder.Feeder_mixed_triple
train_feeder_args:
  full_random_skeleton: True
  data_path: 
    ntu-rgb+d: /home/we/Desktop/Alvaro/code/CrosSCLR/data/NTU60_frame50_rotated/xview/train_position.npy
    smplx_42: /home/we/Desktop/Alvaro/code/CrosSCLR/data/NTU60_smplx42_Metrabs_frame50/xview/train_position.npy
  label_path: /home/we/Desktop/Alvaro/code/CrosSCLR/data/NTU-RGB-D/xview/train_label.pkl
  shear_amplitude: 0.5
  temperal_padding_ratio: 6
  factor: 0.001
  factor_ntu: False
  mmap: True

# model
model: net.aimclr.AimCLR
model_args:
  skeletons:
    - ntu-rgb+d
    - smplx_42
  base_encoder: net.st_gcn_flex.FlexModel
  pretrain: True
  feature_dim: 128
  queue_size: 32768
  momentum: 0.999
  Temperature: 0.07
  mlp: True
  in_channels: 3
  hidden_channels: 16 # 1/4 x channels of standard stgcn
  hidden_dim: 256
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 1e-4
base_lr: 0.1
optimizer: SGD
step: [250]

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 300
start_epoch: 0
stream: 'bone'

# nearest neighbor mining
topk: 1
mining_epoch: 150

# log
save_interval: 5
eval_interval: -1
