# command line: /home/we/.conda/envs/crossclr/lib/python3.8/site-packages/ipykernel_launcher.py --f=/home/we/.local/share/jupyter/runtime/kernel-v2-826426gfk6HKXzu6V4.json

base_lr: 0.1
batch_size: 128
context: true
cross_epoch: 150
device: cpu
eval_interval: -1
model: net.crossclr_3views.CrosSCLR
model_args:
    Temperature: 0.07
    base_encoder: net.st_gcn.Model
    dropout: 0.5
    edge_importance_weighting: true
    embeddings_per_batch: 128
    feature_dim: 128
    graph_args:
        layout: ntu-rgb+d
        strategy: spatial
    hidden_channels: 16
    hidden_dim: 256
    in_channels: 3
    mlp: true
    momentum: 0.999
    num_class: 60
    plot_interval: 10
    pretrain: true
    queue_size: 32768
nesterov: false
num_epoch: 300
optimizer: SGD
print_log: false
save_interval: 5
save_log: false
start_epoch: 0
step:
- 250
test_batch_size: 128
topk: 1
use_gpu: false
view: all
weight_decay: 1e-4
weights: work_dir/crossclr_3views/1_ground_xview_frame50_channel16_epoch300_cross150/epoch150_model.pt
work_dir: embeddings/extractor_work_dir
